### ISSUE TITLE
Problem with neighborsForVertex

### ISSUE THREAD

**Issue by CurlyHeir** [davecom/SwiftGraph#14]
Hi, 
I tried to use this library for PERT https://en.wikipedia.org/wiki/Program_evaluation_and_review_technique

i have something like this: 
![Graph](https://cloud.githubusercontent.com/assets/7043158/23003890/d4dceeee-f3f3-11e6-99ac-b647fdacb73b.jpg)
code: 
```
    let A = Activity(a: 1,m: 2,b: 3, name: "A")
    let B = Activity(a: 2,m: 3,b: 4, name: "B")
    let C = Activity(a: 1, m: 2, b: 3, name: "C")
    let D = Activity(a: 1, m: 2, b: 3, name: "D")
    let E = Activity(a: 3, m: 4, b: 5, name: "E")
    let F = Activity(a: 2, m: 4, b: 6, name: "F")
    let G = Activity(a: 1, m: 3, b: 5, name: "G")
    let H = Activity(a: 3, m: 5, b: 7, name: "H")
    let I = Activity(a: 5, m: 7, b: 9, name: "I")
    
    let graph = UnweightedGraph<Activity>(vertices: [A,B,C,D,E,F,G,H,I])
    graph.addEdge(from: A, to: C, directed: true)
    graph.addEdge(from: A, to: D, directed: true)
    graph.addEdge(from: B, to: E, directed: true)
    graph.addEdge(from: D, to: F, directed: true)
    graph.addEdge(from: E, to: F, directed: true)
    graph.addEdge(from: C, to: G, directed: true)
    graph.addEdge(from: C, to: H, directed: true)
    graph.addEdge(from: F, to: I, directed: true)
    graph.addEdge(from: H, to: I, directed: true)
    
    print(graph.neighborsForVertex(E) ?? [])
```

```

struct Activity {
    let a: Int
    let m: Int
    let b: Int
    let name: String
}

extension Activity: Equatable {
    
    func estimationTime() -> Double {
        let time  = a + 4 * m + b
        return Double(time) / 6.0
    }
    
    func standardVariation() -> Double {
        let time = b - a
        return Double(time) / 6.0
    }
    
    //MARK: Equatable
    static public func ==(lhs: Activity, rhs: Activity) -> Bool {
        return lhs.estimationTime() == rhs.estimationTime()
    }
}
```

neightbors for E prints me something like: 
[PERT.Activity(a: 3, m: 4, b: 5, name: "E"), PERT.Activity(a: 5, m: 7, b: 9, name: "I")]

Maybe i missunderstood something, but i think its not working correctly

**Comment by davecom** [comment]
@CurlyHeir The problem is that the location of vertices is looked up by checking for equality and by your definition of equality (`==`) several of your vertices return equivalent. Therefore when edges are added, they end up pointing from and to equivalent but unexpected vertices. If I change your equality check to:
```swift
static public func ==(lhs: Activity, rhs: Activity) -> Bool {
  return lhs.estimationTime() == rhs.estimationTime() && lhs.name == rhs.name
}
```
things work as expected. An alternative to changing your equality method is to keep track of each vertice's integer index and add edges directly between integer indexes (i.e. `graph.addEdge(from: 4, to: 6, directed: true)`). If you work exclusively in integer indexes, you won't face this lookup problem.

**Comment by CurlyHeir** [comment]
Thank you for reply an help! Now it works fine :)
