### ISSUE TITLE
Add Support for the Swift 4 Serialization Mechanisms

### ISSUE THREAD

**Issue by davecom** [davecom/SwiftGraph#22]

**Comment by yoiang** [comment]
Hey @davecom, have you put any thought to this yet? Otherwise I can start poking and post some thoughts. This'll be great for an ongoing project!

**Comment by davecom** [comment]
Hi @yoiang,
I haven't had time to look into this extensively. But I think it should be possible to make an extension of Graph (or perhaps separate ones for UnweightedGraph and WeightedGraph) that conditionally conforms to Codable when the vertices (and for WeightedGraph, weights) conform to Codable as well.
You could try that first... If you do let us know if it works or not.
Best,
Dave

**Comment by yoiang** [comment]
That's the path I thought you'd meant and would prefer as well! I also meant if you'd had a chance to think about the nuts and bolts of correlating individual objects once they are serialized into their data representation. 

I imagine we'll have to use some sort of hash reference system so that arbitrary vertice objects can refer to arbitrary edge objects and vice versa.

**Comment by davecom** [comment]
Because SwiftGraph uses a hybrid adjacency list model, I'm not sure any such extra machinery is actually necessary. As long as the Arrays representing all vertices and all edges are encoded and decoded in the same order, I think we should be good.
