### ISSUE TITLE
Implement Graph Union operation

### ISSUE THREAD

**Issue by ferranpujolcamins** [davecom/SwiftGraph#35]
I'm interested in contributing graph union operation: http://mathworld.wolfram.com/GraphUnion.html
It should be quite straightforward for unweighted graphs. For weighted graphs, we need to add different ways to handle weight conflicts on common edges:

- Built in "reducers": sum, average, min, max.
- Support custom reducers.
- Report conflicts as exceptions or errors (this could be modeled as a reducer too)

My only question is how to compute the disjoint set union. You store edges and nodes as Array. Is building a Set from one array, use [Set.formUnion](https://developer.apple.com/documentation/swift/set/2853361-formunion) and then convert back to array a good solution? I can't find info on computational complexity for these operations.

PS: maybe it makes more sense for the weighted case to just treat edges between same nodes as distinct edges. Then add another operation that merges edges between common nodes.

**Comment by davecom** [comment]
Hi @ferranpujolcamins ,
I think this should not be a problem to add via an extension to `Graph`. If we're talking about a disjoint union, then I don't see why we need to treat `WeightedGraph`s specially. If it's a disjoint union, then why do the edges need to be combined? Maybe I'm missing something. If we're talking about a non-disjoint union then I think your solution makes sense. Regarding using `Set.formUnion`—I don't think there would be a problem for performance reasons. There is a problem conceptually though. Users are able to add nodes that are equal purposefully. Imagine a user adding a set of nodes and adding the node "A" (String) twice. He might really mean to do so. Each node is a distinct node with its own assigned internal index (integer) even though it ostensibly is equivalent. Currently this is allowed in SwiftGraph. If we are to disallow it, it might break certain existing applications. So, the issue is that if we convert to a Set, we will be dropping equal nodes that are currently allowed to exist and be distinct in SwiftGraph.

Anyway, feel free to add this in in a separate extension(s) in a new file. Something like `Union.swift`

Thank you for the interest and for bringing this up as an issue.
Best,
David

**Comment by ferranpujolcamins** [comment]
Hi @davecom, thank you for your comments. I'll think of all this and maybe issue a small proof of concept PR.

I'm wondering: why are nodes stored in an array? What seems weird to me is that the index of nodes is exposed in the api, yet removing a vertex modifies the indexes of all nodes.
Did I get this right? Or is there something I'm missing?

**Comment by davecom** [comment]
@ferranpujolcamins 
You are correct. It is compromise. The typical ways to store a graph data structure are either with an adjacency matrix (2d array of vertices, the intersection is where you store weight values for a weighted graph) or adjacency lists (this project). In the adjacency list model you store the vertices and a list of edges that connects each vertex to its neighbors. This could be achieved with a dictionary with the vertices as the keys and the values an array of edges, but it would then require that vertices be `Hashable`, a requirement I did not want. An alternative would be an ordered set, but the Swift standard library has no ordered set type and again this would require vertices to be `Hashable`. Using an array has other benefits as well: it allows nodes that are equivalent to be added twice (like we discussed earlier in the thread) and represent unique nodes. Imagine loading a quick and dirty data set of the cities in the United States not marked by state and just by Strings. You would have 26 "Springfield" nodes. You wouldn't want to collapse that into a single node. For some simple data processing tasks this therefore is convenient. The benefit of exposing both the `Vertex` and its index is that both internal to the project and external to the project you can refer to a node by its index, a simple `Int` with O(1) lookup times, instead of having to do a linear search through the array every time you do any operation. This is typically smaller to store external to the graph's API as well then storing duplicates of the vertices which can be complex data types in some instances. But, you're right, storing indices gets messed up if you delete a node. So, it's a compromise, chiefly from the desire to not require the vertices to be `Hashable`. You can find a more in-depth explanation of the design of SwiftGraph in Chapter 4 of my book, available for free here: https://manning-content.s3.amazonaws.com/download/1/10d2f0d-db29-4c85-bed1-94b80a3c0ef7/Chapter4SAMPLE.pdf

**Comment by ferranpujolcamins** [comment]
Hi @davecom,
thank you for your explanations. I understand your design choices.

What if we assigned each vertex an incremental int as index, instead of tying the vertex id to its position on the array? We just need to store vertexs in a dictionary indexed by Ints. Something like this:
``` swift
class Graph<V: Equatable> {
  
    var vertices: [Int : V] = [Int : V]()
    var lastIndex = 0;
  
    public func vertexAtIndex(_ index: Int) -> V {
        return vertices[index]!
    }
    
    public func addVertex(_ v: V) -> Int {
        lastIndex += 1
        vertices[lastIndex] = v
        edges.append([Edge]())
        return vertices.count - 1
    }
    
    // ...
}
```

This way vertexs have an index that does not change when the graph is mutated. Of course, the tradeof is that some operations become O(n) instead of O(1). What do you think?

**Comment by davecom** [comment]
Yeah we absolutely can't make that trade off. Having O(1) lookups is essential.

**Comment by ferranpujolcamins** [comment]
Ok. 

Maybe I've thrown to the discussion too many topics. Let me make a simpler proposal from what we have already discussed:

- I'm issuing a proof of concept PR so we have something to further discuss on (this POC PR does not need to be merged).
- By now let us focus only on disjoint union, it is the use case I actually need.
- Let's just focus on the unweighted case by now.
- Since the current Graph implementation allows for repeated values in Vertexs array, It'd be weird to add a disjoint union in it. I propose to implement a new DisjointGraph subclass that implements [SetAlgebra protocol](https://developer.apple.com/documentation/swift/setalgebra). This also means that I'm not changing current Graph implementation nor interface.
- I'm doing a naive implementation by now. Let's postpone discussion about performance / requirements on types tradeoff for later.

Does this sounds like a plan to you?

**Comment by ferranpujolcamins** [comment]
By the way, my end motivation is to design a DSL thet let users describe a Tree by listing individual branches. For example, the following would define an undirected K4 graph:
```swift
let process = Process([
    A --- B --- C --- D,
    D --- A --- C,
    D --- B
])
```

**Comment by davecom** [comment]
Hi @ferranpujolcamins,
I've had to refactor some of your class with the change of Graph from Class to protocol. I managed to get all of the tests to pass. The trickiest issue is that a self-cycle will now just be one edge, whereas in the last version (I think wrongly) it was becoming two. Let me know if you think this current version is correct.
Thanks,
David

**Comment by ferranpujolcamins** [comment]
Oh I'm sorry I didn't realize your comment. Let me check :)

**Comment by ferranpujolcamins** [comment]
I think it's ok!
