### ISSUE TITLE
Swift 5 Support

### ISSUE THREAD

**Issue by davecom** [davecom/SwiftGraph#62]
Check all is well on Swift 5 after the final release of it ships with Xcode 10.2 and if any changes are needed. Review the changes in recent pull requests by @ZevEisenberg and @ferranpujolcamins .

Development for Swift 5/SwiftGraph 2.1 is taking place in the release2.1/swift5 branch.

**Comment by ferranpujolcamins** [comment]
- [ ] Add xcode 10.2 and swift 5 to CI config

**Comment by davecom** [comment]
@ferranpujolcamins I updated a bunch of the code in UniqueElementGraph that was not building in Swift 5 and now several of the tests for Union and UniqueElementsGraph are failing. I don't know if I broke something or if it was already broken. Can you take a look at it? I'm not very familiar with these tests/code. Thanks in advance.

**Comment by ferranpujolcamins** [comment]
I'm having a look at the original issues. At first glance they seem a regression in the swift compiler.

**Comment by ferranpujolcamins** [comment]
I still think it's an Xcode bug. Can you:

1. Roll back the release branch to `ae1a8f3f268ef84b7f30738921b6aa5ed6dfe009`
2. Update the project to Swift 5 without any code change
3. Commit to the release branch
4. Open a bug to the radar pointing to the release branch, also ask for a temporary workaround because otherwise we cannot ship until Xcode 10.3. Remember to note that the project builds fine with swift cli.

**Comment by ferranpujolcamins** [comment]
I was wrong, from the cli I get the same error (I was still using swift 4). So maybe it's not an Xcode bug.

**Comment by ferranpujolcamins** [comment]
So, it seems there's a bug related to convenience initializer and associated types. I filed it [here](https://bugs.swift.org/browse/SR-10434).

A workaround can be to turn the initializers into static factory methods.

**Comment by ferranpujolcamins** [comment]
> Turning these initializers into static factory methods can be a workaround.

Yes, I can confirm this fixes the problem
