### ISSUE TITLE
Graphs with Int Vertices have Ambiguous Method Calls

### ISSUE THREAD

**Issue by peterkos** [davecom/SwiftGraph#7]
Is there a reason to make the convenience methods public?
I've had a small issue when attempting to create graphs with them, as sometimes they work and sometimes they don't (depending on the type used).

For instance, take the following graph declaration:

``` swift
var graph:UnweightedGraph<String> = UnweightedGraph<String>()

graph.addVertex("Hello")
graph.addVertex("World")
graph.addEdge("Hello", to: "World")

print(graph.description)
```

This prints the graph correctly.
However, when replacing the graph type from `String` to `Int`, the method (and the other convenience methods for addEdge) throws an ambiguous use error.

``` swift
var graph2: UnweightedGraph<Int> = UnweightedGraph<Int>()

graph2.addVertex(123)
graph2.addVertex(456)
graph2.addEdge(0, to: 1, directed: false)        // Throws ambiguous use error
graph2.addEdge(0, to: 1)                         // Throws ambiguous use error
graph2.addEdge(UnweightedEdge.init(u: 0, v: 1, directed: false)) // Works fine (as intended)

print(graph2.description)
```

**Comment by davecom** [comment]
It's an interesting issue. It's specific to graphs with vertices of type Int, because the built-in indices are also of type Int (and the two methods have the same name/parameter names). ]For the present, I can offer two solutions:
- Do not use vertices of type Int
- If you need Int vertices wrap your Int in a class or struct that implements Comparable and Summable

Longer term I could see possibly changing the name of the convenience methods, although this would break backwards compatibility (better sooner rather than later)!
